import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { geistMono, geistSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Zoo managment app",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-hidden`}
      >
        <ThemeProvider>
          <ThemeToggle className="absolute right-2 top-2" />
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
